### ISSUE TITLE
Would it be possible to keep libpython.a?

### ISSUE THREAD

**Issue by rdb** [pypa/manylinux#91] opened 2017-01-11 00:00 UTC
The application I'm trying to build has a particular need to embed the interpreter into an executable, which requires static linking with libpython.

Would it perhaps be possible not to delete libpython.a from the image, but keep it in the _internal directory for those who are absolutely certain they need to use it?

**Comment by Moguri** [comment] 2018-04-28 19:30
Can we get some discussion going on this? Is this something that is a complete non-starter, or are pull requests welcome? What are the issues/concerns with something like this? Larger containers? Are wheels affected? Maybe this is something we can discuss for manylinux2010 if there is hesitation to have it as part of manylinux1.

**Comment by njsmith** [comment] 2018-04-28 21:07
I think this is out of scope for manylinux, since it's about building portable binaries of your application, not about building manylinux wheels. You're welcome to reuse our scripts and so on, but i don't want to add it to the image. It's a lot of extra download weight.

**Comment by njsmith** [comment] 2018-04-28 21:07
Note that if you start with something like the "holy build box" then building a copy of python to embed is probably not too difficult?

**Comment by njsmith** [comment] 2018-04-28 22:28
Huh, so you're... shipping a copy of Python, inside your Python wheels?

**Comment by rdb** [comment] 2018-04-29 14:40
Sort of; we're shipping a stub executable that embeds the interpreter and runs whatever Python bytecode is appended to the end of the executable, similar to what py2exe does. This allows users to easily compile their Python code into executables; we just need to grab the appropriate .whl of the dependency packages and inject their bytecode into the stub.

Compiling this stub requires linking in `libpython.a`. It would save us a significant maintenance burden if there could be some easy way to have manylinux1 contain the `libpython.a` file somewhere. If not, we'll just have to continue to maintain our own fork of manylinux.  That said, perhaps it could be an option to enable when building the docker images, eg. via an environment variable?

**Comment by SylvainCorlay** [comment] 2020-02-14 18:52
@Moguri we are finding the exact same usecase for our project and would love to see `libpython.a` included in the docker image.

Note that we are currently building our own docker image from a fork of the manylinux repository. Unfortunately, your base docker image is private making it not reproducible.

**Comment by Moguri** [comment] 2020-02-15 22:52
@SylvainCorlay The dockerfile we are using can be found [here](https://github.com/panda3d/buildbot-panda3d/blob/master/dockerfiles/manylinux1-x86_64).

**Comment by SylvainCorlay** [comment] 2020-02-15 23:09
@Moguri thanks. I meant to say that the base docker image of the official manylinux (https://github.com/pypa/manylinux/blob/master/docker/Dockerfile-x86_64#L2) is private.

**Comment by rdb** [comment] 2021-02-17 18:42
I would kindly like to resubmit this for consideration.  Until now, we have been able to build our own fork of manylinux that removes the `rm libpython*.a` command, but we would like to start offering aarch64 wheels, and it turns out to be prohibitive for us to build our own aarch64 manylinux image (we don't have access to the right hardware, and an attempt to build via qemu ground to a complete halt after 12 hours).

It would really help us a lot to have libpython kept in the Docker image, even if it's moved somewhere totally out of sight, so that we can continue building our executable that embeds the Python interpreter.

**Comment by Helveg** [comment] 2021-10-02 19:55
Kind of a counterargument to just including it. I didn't know much about the downsides of building against a shared mode interpreter and with `find . -name libpython*.so` no location would've been out of sight.

**Comment by rdb** [comment] 2022-01-06 20:32
Annual bump.  This would be a huge help for us.  Our library includes a binary that embeds the interpreter, which requires linking against libpython.a.  So far we are using a modified version of manylinux for i686 and x86_64, but it is prohibitively difficult to build our own manylinux for some of the architectures that require cross-compilation.

Is there anything we can do to help move this issue along?

**Comment by mayeut** [comment] 2022-01-08 12:58
@rdb,

just on a side, I think travis-ci now offers again free usage for aarch64, s390x & ppc64le as part of their [Partner Queue](https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution)

> Is there anything we can do to help move this issue along?

Yes there is. I'll outline what would be acceptable for a PR:
- to prevent misusage of the libraries, they should not be available as a default (i.e. requires a step to make them available, probably through an helper script, other propositions welcome).
- the size of the image (both compressed & uncompressed) shall not grow too much (let's say 0.5% as a threshold here) as this would impact 99.5% of users that probably don't need those (if I'm wrong, we can revisit the threshold a bit).

**Comment by mathstuf** [comment] 2022-01-08 15:06
> to prevent misusage of the libraries, they should not be available as a default (i.e. requires a step to make them available, probably through an helper script, other propositions welcome).

Build systems in use in the wild will adapt and seek the library out as needed (e.g., I'd expect CMake's `FindPython` to gain support at some point). Do you mean "more than a simple `-lpython` flag" as the limit here or must one do something like extract a password-protected zip to make the library available?

**Comment by rdb** [comment] 2022-01-08 15:08
Thanks! I'll get to work on that.  No worries, I'll do it in a way that build systems or users won't be able to find it automatically.

From a quick experiment, all the libraries compressed together (so that they share a dictionary) makes less than 3 MB, well under the 0.5 % threshold.  However, because of Docker's layer system and because the Python versions are all built separately, realising these gains is a little trickier.  Hmm.

**Comment by mayeut** [comment] 2022-01-08 15:48
> From a quick experiment, all the libraries compressed together (so that they share a dictionary) makes less than 3 MB, well under the 0.5 % threshold. 

Good !

> However, because of Docker's layer system and because the Python versions are all built separately, realising these gains is a little trickier. Hmm.

All CPythons versions are copied in a single step in the final image for various reasons. That means you should be able to achieve what you observed. The CPython individual layers are used for build cache only and it's less of an issue for them to grow a bit more. End users will never pull those layers.
The only layer that matters is:

https://github.com/pypa/manylinux/blob/b3aff190a4eb9121f451baab86e8ae7475a09ca9/docker/Dockerfile#L154

**Closed** 2022-01-09 15:00 UTC
Labels: enhancement, help wanted
