### ISSUE TITLE
Python 3.8: ABI Tag Changed

### ISSUE THREAD

**Issue by ax3l** [pypa/manylinux#393] opened 2019-11-17 18:52 UTC
Hi,

am looking at the latest python 3.8 changes:
```
$ docker run -it quay.io/pypa/manylinux2010_x86_64
[root@180d8940e67b /]# ls /opt/python
cp27-cp27m  cp27-cp27mu  cp34-cp34m  cp35-cp35m  cp36-cp36m  cp37-cp37m  cp38-cp38
```

I noticed that the CPython abi tag has changed from `cp37m` to `cp38` (without the `m`) in the latest images.
According to google this means Python 3.8 is not compiled with `pymalloc`, should I be concerned?

**Comment by rdb** [comment] 2019-11-17 18:53
Duplicate of #372.  Python 3.8 removed the `m` ABI flag because the ABI is not different between the pymalloc and the regular version.

**Comment by ax3l** [comment] 2019-11-17 18:53
Oh, found it. Sorry!
https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes

**Closed** 2019-11-17 18:55 UTC
