### ISSUE TITLE
Support PEP 600 manylinux_X_Y for glibc X.Y 

### ISSUE THREAD

**Issue by mattip** [pypa/manylinux#501] opened 2020-03-20 08:40 UTC
xref gh-494. Is there interest in starting a manylinux_X_Y branch to support PEP 600 glibc-based manylinux numbering? I am particularly interested in manylinux_2_18 for glibc2.18 for other architectures. Rather than open a separate branch for each glibc version, I think we can adjust the tooling. TODO:
- add manylinux_X_Y support to auditwheel. Version 3.1 only supports 'linux_x86_64', 'manylinux1_x86_64', 'manylinux2010_x86_64', 'manylinux2014_x86_64' as arguments to `auditwheel --plat`
- add manylinux_X_Y support to platform, update pip and wheel to use this new version of platform (wheel as of today still uses `pep425tags.py`
- wait for releases of pip, wheel
- update this repo

@njsmith any thoughts?

**Comment by mayeut** [comment] 2020-03-28 11:36
What's hard is to find the distribution which ensure a manylinux_X_Y compatibility while still being supported and having all the tools needed...

**Comment by mayeut** [comment] 2020-04-25 14:10
@mattip, I started to work on something parsing different distros to get compatibility with PEP600: https://github.com/mayeut/pep600_compliance
It's far from being complete but has the upside of not requiring parsing manually the distrowatch database.

**Comment by mayeut** [comment] 2021-02-14 15:51
closing as duplicate of #542

**Closed by mayeut** 2021-02-14 15:51 UTC
