### ISSUE TITLE
Update auditwheel in the Docker containers

### ISSUE THREAD

**Issue by saghul** [pypa/manylinux#66] opened 2016-05-27 22:25 UTC
Hi there,

While using the suggested Docker containers I ran into a problem, I couldn't upload some of the wheels it had generated. Turns out, the problem was a broken rename by auditwheel 1.3.0, the version installed in the container. Updating to 1.4.0 solves it (looks like [this commit](https://github.com/pypa/auditwheel/commit/36cf8ea542162f862f0bb20ad51c823d403d515e), so it might be a good idea to update the container image.

FTR, the broken renamed wheels looked like this:

```
 $  twine upload -r pypi wheelhouse/*.whl
Uploading distributions to https://pypi.python.org/pypi
Uploading pyuv-1.3.0-cp27-cp27m-linux_i686.manylinux1__i686.whl
HTTPError: 400 Client Error: Binary wheel for an unsupported platform for url: https://pypi.python.org/pypi
```

**Comment by ogrisel** [comment] 2016-05-28 09:02
I triggered a new build for the manylinux image:

https://travis-ci.org/pypa/manylinux/builds/133560850

Once it's green the new docker images with auditwheel 1.4.0 should be online.

**Comment by ogrisel** [comment] 2016-05-28 10:09
Actually it did not work for some reason (besides the travis timeout which did not prevent the build and upload to complete):

The script did not upgrade to the latest version of auditwheel: 1.3.0 is still there in the image.

**Comment by ogrisel** [comment] 2016-05-28 10:15
Actually the upload was ignored with the following warnings:

```
Error response from daemon: Conflict: Tag latest is already set to image dda75941085124f3198d1f96385bf1136abbc227ef01efb6489b03a6122c47a3, if you want to replace it, please use -f option
The push refers to a repository [quay.io/pypa/manylinux1_i686] (len: 1)
Error response from daemon: Conflict: Tag latest is already set to image f117a91d3987f94a30a4958bd8ce343fc0644aedee9d9c50bdf1bdefb81ece8c, if you want to replace it, please use -f option
The push refers to a repository [quay.io/pypa/manylinux1_x86_64] (len: 1)
```

**Comment by ogrisel** [comment] 2016-05-28 10:30
@rmcgibbo @njsmith @matthew-brett it seems we already had this issue in the past but I don't find it in the issue tracker. Do you remember anything about that? Shall we do `docker tag -f`?

**Comment by njsmith** [comment] 2016-05-28 15:17
Just to restate the problem to see if I understand, the issue is that right now we have a 1-1 making between commits to our git repo and images uploaded to quay.io, and trying to rebuild a commit in place is causing that to freak out? Specifically because we tag each image with the git commit is, so this causes us to attempt to reuse a tag?

I don't think we should push -f, on the grounds that pinning a manylinux image is a reasonable thing for users to potentially want to do, and they might pin by the tag we're using.

If we want the click-rebuild workflow to work, we could give up on our current tagging scheme -- I don't know how useful it is anyway, and it's possible to pin by docker image id instead of by tag anyway.

The other workflow for handling this kind of rebuild is to submit a pr with an empty commit. (`git commit --allow-empty` iirc), so we get the usual pr test-before-merge logic.

**Comment by njsmith** [comment] 2016-05-29 17:59
@ogrisel: It looks like you direct-pushed an empty commit to trigger the rebuild? Should this be closed?

**Comment by ogrisel** [comment] 2016-05-30 07:56
> @ogrisel: It looks like you direct-pushed an empty commit to trigger the rebuild? Should this be closed?

I got the "Error response from daemon: Conflict: Tag latest is already set" error precisely when I pushed the empty commit to trigger the image update.

**Comment by ogrisel** [comment] 2016-06-13 07:56
A more recent build by @njsmith is green but got the same deployment error:

https://travis-ci.org/pypa/manylinux/builds/134894243#L5371

**Comment by njsmith** [comment] 2016-06-13 18:54
I guess we do need `push -f` then? Maybe docker changed their command line semantics? Docker is mysterious :-/

**Comment by ogrisel** [comment] 2017-01-03 23:23
Closing as deployment seems to be working from the travis builds on the master branch. I am not sure who fixed it.

**Closed by ogrisel** 2017-01-03 23:23 UTC
