### ISSUE TITLE
manylinux2014 docker image doesn't support numpy

### ISSUE THREAD

**Issue by snnn** [pypa/manylinux#548] opened 2020-04-22 19:06 UTC
Install numpy from source failed at:
```
 numpy/core/src/npymath/npy_math_internal.h.src: In function ‘npy_cacoshf’:
    numpy/core/src/npymath/npy_math_internal.h.src:482:12: internal compiler error: Segmentation fault
         return @kind@@c@(x, y);
                ^~~~~~~~~~~~~~~
    Please submit a full bug report,
```

It's a known toolchain bug. see:

1. https://github.com/numpy/numpy/issues/13622
2. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90075

**Comment by mayeut** [comment] 2020-05-02 13:18
duplicate of #494

**Closed by mayeut** 2020-05-02 13:18 UTC
