### ISSUE TITLE
Linking to libpython

### ISSUE THREAD

**Issue by alex-eri** [pypa/manylinux#793] opened 2020-10-05 09:12 UTC
I want to build cx-Freeze against manylinux, but
```
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/_internal/cpython-3.7.9/include/python3.7m -c source/bases/Console.c -o build/temp.linux-x86_64-3.7/source/bases/Console.o
    creating build/lib.linux-x86_64-3.7/cx_Freeze/bases
    gcc -pthread build/temp.linux-x86_64-3.7/source/bases/Console.o -L/opt/_internal/cpython-3.7.9/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -o build/lib.linux-x86_64-3.7/cx_Freeze/bases/Console -Xlinker -export-dynamic -lcrypt -lpthread -ldl -lutil -lrt -lm -s
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lpython3.7m
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

```

**Comment by madig** [comment] 2020-10-25 19:08
I think you're not supposed to link to libpython: https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1.

**Comment by mayeut** [comment] 2022-01-08 18:08
duplicate of https://github.com/pypa/manylinux/issues/1149

**Closed by mayeut** 2022-01-08 18:08 UTC
