### ISSUE TITLE
Cover the rest of the archs from PEP 599

### ISSUE THREAD

**Issue by webknjaz** [pypa/manylinux#1029] opened 2021-03-05 11:37 UTC
armv7l (that a lot of raspberries use because the official 64-bit kernel is still in beta) and ppc64 are present in the PEP but the images for these aren't built.

I haven't found any discussion mentioning them so I just wanted to have someplace documenting why they are missing.

My wild guess is that it's because Travis CI doesn't provide them. Any other reasons? It looks like it should be possible to build them with QEMU under GHA, no?

**Comment by mayeut** [comment] 2021-03-09 07:13
@webknjaz, this is mostly a duplicate of #84
I'll move your questions there.

**Closed by mayeut** 2021-03-09 07:13 UTC
Labels: duplicate, enhancement, question
